### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [www-chao-fun/chaofun-app#228]
请问是否可以在 F-Droid 上发布应用？

**Comment by cijianzy** [comment]
@linsui 可以的。

**Comment by cijianzy** [comment]
@linsui 可行的，主要是分享/推送的，工作量可能有点大。

**Comment by linsui** [comment]
有点复杂，不过只要没有核心功能依赖这些库就好。我试试看。

**Comment by linsui** [comment]
一方面我自己想要使用更多 FOSS 的应用，另一方面也希望可以方便国内用户。同时，如果 F-Droid 可以有更多国内应用，也可以吸引更多国内 Android 用户使用 F-Droid。

**Comment by cijianzy** [comment]
@linsui ，谢谢你，红领巾。

**Comment by linsui** [comment]
开源嘛，想用就自己动手 :laughing:

**Comment by linsui** [comment]
似乎网站依然不能访问？我连上了一次然后就连不上了。APP 一直网络异常。

**Comment by cijianzy** [comment]
@linsui 收到，我更新一下。

**Comment by linsui** [comment]
谢谢，不过代码里的地址还没有更新，构建出来的 apk 连不上服务器。

**Comment by cijianzy** [comment]
@linsui 嗷嗷，我现在改一下。

**Comment by cijianzy** [comment]
@linsui 已经改好地址 userHelper 问题也解决，辛苦再看看好没好

**Comment by linsui** [comment]
谢谢！我试一下!

**Comment by linsui** [comment]
apk 测试了一下没有问题。请问我可以在这个存储库里添加 fastlane 元数据吗？F-Droid 可以从这里抓取应用描述。如果可以我开个 PR。

**Comment by cijianzy** [comment]
可以

**Comment by linsui** [comment]
大概一周内应用会进入 F-Droid 的存储库。谢谢帮助！
